### ISSUE TITLE
how to setup documentation in readme.md

### ISSUE THREAD

**Issue by bas080** [SpoonX/spoonx-tools#5]
Currently i use the aurelia component seed. How would I go about replacing that with the spoonx-tools?

**Comment by doktordirk** [comment]
what's aurelia component seed? 

anyways, maybe you mean https://github.com/SpoonX/aurelia-plugin-skeleton ?

**Comment by doktordirk** [comment]
ps: i might have been a bit lazy with adding documentation to either of them

**Comment by bas080** [comment]
@doktordirk, our own plugin skeleton. Now that is cool

**Comment by doktordirk** [comment]
well, it could use some love :smile:

**Comment by bas080** [comment]
If correct ours is competing with aurelia's plugin skeleton. Why should people use SpoonX's plugin skeleton?

**Comment by doktordirk** [comment]
there is no competition. this is/should be/will be more a starter repo for our plugins with our eslint rules etc

**Comment by RWOverdijk** [comment]
Closing this as I think the question has been answered.
